package Lecture_33_recursion_on_String_find_subsequences_question_sol;

import java.util.ArrayList;

//Q1 Given a string , WAP  to return all its subsequences in an arraylist . A string is a subsequences of a given String
// than is generated by deleting some character of a given string without changing its oder
public class Q1 {
    static ArrayList<String>getSSQ(String s){
        ArrayList<String> ans = new ArrayList<>();
        //base case
              if(s.length()==0){
                  ans.add("");
                  return ans;
              }
        char curr = s.charAt(0);
        ArrayList<String> smallAns = getSSQ(s.substring(1));
        for(String ss: smallAns){
            ans.add(ss);
            ans.add(curr+ss);
        }
        return  ans;
    }
    public static void main(String []args){
            ArrayList<String> ans =getSSQ("abc");
            for(String ss:ans){
                System.out.println(ss );
            }
    }

}
